---
# tasks file for ansible-maas

- name: Install MAAS
  ansible.builtin.include_tasks: install.yml

- name: Configure MAAS
  ansible.builtin.include_tasks: config.yml

- name: Manage MAAS users
  ansible.builtin.include_tasks: users.yml
  when: maas_setup_user|bool
